### ISSUE TITLE
HTML5Shiv and Respond.JS only needed for IE8 and lower

### ISSUE THREAD

**Issue by coliff** [Rundiz/bootstrap-basic#10]
At the moment it loads HTML5Shiv and Respond.JS for all browsers. Those polyfills are only needed for IE8 and lower though. I propose that those files should be deleted from the project and loaded via a CDN with a conditional statement like:
`<!--[if lt IE 9]><script src="https://cdn.jsdelivr.net/g/html5shiv@3.7.3,respond@1.4.2"></script>`

**Comment by ve3** [comment]
I agree that to make it conditional statement but I don't think it should be deleted and loaded via CDN.

Sometimes admin/developers are use cms like WordPress as intranet web site or some area in the world may have too slow internet connection to use CDN files. I was experienced this problem where I am here.
The slowly internet connection to CDN file can cause page load too slow and bad for user experience.

What do you think?

**Comment by coliff** [comment]
Ok then, if you prefer to do that - it's fine :-)
