### ISSUE TITLE
Support for Localisation

### ISSUE THREAD

**Issue by coliff** [Rundiz/bootstrap-basic#16]
Some strings in the theme are hard-coded in English,for example on the search.php page '_**Search Results for:**_ ' always displays in English even if WordPress is set to French for example.

It would be good to support localisation, though I don't know the exact steps to do that but If you could enable that I can help with providing translated strings for it (if needed). (I found the strings for this page at: https://translate.wordpress.org/projects/wp/dev/fr/default?filters%5Bterm%5D=Search+results+for+&filters%5Buser_login%5D=&filters%5Bstatus%5D=current_or_waiting_or_fuzzy_or_untranslated&filter=Filter&sort%5Bby%5D=priority&sort%5Bhow%5D=desc by the way).

**Comment by coliff** [comment]
UPDATE: I realise now we need to add a fr_FR.mo and fr_FR.po to the 'languages' dir to add support for French. I'll take a look at working on that.

**Comment by ve3** [comment]
:D Is that fixed?

**Comment by coliff** [comment]
I started on it. I'm using https://en-gb.wordpress.org/plugins/loco-translate/ - which works great. I can export the translations as .po and .mo and they work well with your theme. I'm busy with a different project right now so not sure if I'll have time to complete it soon though.
