### ISSUE TITLE
Update to Font Awesome 3.7.0

### ISSUE THREAD

**Issue by coliff** [Rundiz/bootstrap-basic#17]
Update to Font Awesome 3.7.0

**Comment by ve3** [comment]
done.

Do you have user account with wordpress.org? I will add your name in contributors in **Bootstrap Basic 4** > **readme.txt** file.
I'm not sure is this working on WordPress theme like a plugin?

**Comment by coliff** [comment]
That'd be great - thanks :-)  My WordPress username is: christianoliff

**Comment by ve3** [comment]
It's already there. https://github.com/Rundiz/bootstrap-basic4/blob/master/readme.txt
Sorry I just upload the theme before your reply, I think I have to wait until next update.
However the Bootstrap Basic 4 theme did not live and still waiting to approve.
