### ISSUE TITLE
Pagination for WP Query / multiple categories

### ISSUE THREAD

**Issue by RaefWolfe** [Rundiz/bootstrap-basic#21]
I've created a custom query to grab posts from multiple categories, but pagination doesn't work when I do so.

Pagination works on other pages I've created that do not use multiple categories, but it fails with WP Query.

Any fixes / ideas?

> <?php
$args = array(
  'category_name'         => 'raid,raid-homework,player-performance'
); 
$q = new WP_Query($args);
if ( $q->have_posts() ) { 
  while ( $q->have_posts() ) {
	$q->the_post();
	  get_template_part('content-raid', get_post_format());
	// your loop
  }
  bootstrapBasicPagination();
}
?>
> 

To be clear, the page shows the proper number of posts, just no pagination for it.

**Comment by ve3** [comment]
I have no idea about multiple categories.
But in this case you may remove the line that call to `bootstrapBasicPagination();` function and replace with your custom pagination.

**Comment by ve3** [comment]
I've tried this setting and code and it's working.

```php
$args = array(
    'category_name' => 'raid,raid-homework,player-performance',
    'paged' => max(1, get_query_var('paged')),// Add this!
);
```

Don't use `$q = new WP_Query`. Use `$wp_query` instead.

```php
$wp_query = new \WP_Query($args);
if ($wp_query->have_posts()) {
    while ($wp_query->have_posts()) {
        $wp_query->the_post();
        get_template_part('content-raid', get_post_format());
    }// endwhile;
    bootstrapBasicPagination();
}

// add the line below to reset everything to its default.
wp_reset_query();
wp_reset_postdata();
// this will reset the $wp_query to its default value.
```
